# Data Programming in Python | BAIS:6040
# Exam I (25 points)

### Read the following guidelines carefully.

* <b> Do not share this file or contents of it in any form with anyone else.</b> 

* This is an individual test. All the submitted work must be written and compiled entirely by you only. 

* Other than the instructor, <b>no communication about this test with anyone else is allowed</b>. Also, you are allowed to ask the instructor questions with clarification purposes only. 

* The test is Open-notes and CLOSED-Internet. Closed-internet means do not look for solutions online, particualry do not use generative AI to find solutions.

* Answer the questions in order within this notebook. Use only one designated code cell for each question and do not include any unnecessary code. <b>Do not use the print function unless the question specifies that it prints something.</b>

* Observe all rules as specified on the homework assignments.

* When you are finished with all questions, click Kernel > Restart & Run All to create a clean version of the notebook and double check if each code cell has been run as expected. Also, make sure to save the notebook before submitting to ICON. After submitting the notebook, validate that the notebook you submitted is what you intended to submit. You are responsible for any unsaved code in the notebook or corrupt/wrong notebook file.

* By submitting your work in this file <b> you sign the Tippie Honor Code and agree to have followed the rules listed above</b>. Failure to follow the rules will lead to penalty, including a zero for this exam.  

### 1\. (7 points) Run the cell below to create a list <i><b>letters</b></i> of random letters in the alphabet. Do not make any change to <i><b>letters</b></i>.

In [1]:
# Do not make any change to this cell. Just run this cell.
letters = ['q', 'e', 'f', 'q', 'f', 'n', 'o', 'e', 'g', 'm', 'i', 'm', 'i',
           'n', 'e', 'g', 'r', 'o', 'l', 'j', 'z', 'j', 'h', 'k', 'm', 'n',
           'g', 't', 'o', 'k', 'u', 'e', 'o', 's', 'y', 'v', 'x', 'g', 'i',
           's', 'q', 'h', 't', 'e', 'e', 'c', 'n', 'l', 'j', 'z', 'e', 'u',
           'o', 'o', 'l', 'q', 'x', 'f', 'u', 'r', 'v', 'c', 'r', 'z', 'h',
           'j', 'h', 'z', 'f', 'd', 'o', 'l', 'k', 't', 'k', 'y', 's', 't',
           'b', 'w', 'h', 'u', 'e', 'o', 'z', 'r', 'a', 't', 'e', 'j', 'z',
           'u', 'd', 's', 'o', 'c', 'v', 'd', 's', 's']

<b>1.1 (1 pt)</b> Get the number of letters in <i><b>letters</b></i> and save it in the variable <i><b>num_letters</b></i>. (Do not manually count.) 

In [4]:
# Your answer here
num_letters = len(letters)

In [5]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
num_letters

100

<b>1.2 (1 pt)</b> Get the number of <u><b>unique</b></u> letters in <i><b>letters</b></i> and save it in the variable <i><b>num_unique_letters</b></i>. (Do not manually count.)

In [9]:
# Your answer here
letters_set = set(letters);
num_unique_letters = len(letters_set);

In [10]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
num_unique_letters

25

<b>1.3 (2 pts)</b> Write a <b>for loop</b> that prints only the letters at every 5th index position including 0 (e.g., 0, 5, 10, …, 95) in the format "[INDEX] LETTER" where INDEX is the index position for the letter and LETTER is the letter in uppercase. The printed pairs of index and letter are separated by a space (' '). 

The printed output must look as follows: 

In [20]:
# Your answer here
for i in range(len(letters)):
    if(i%5 == 0):
        item = letters[i];
        print("[{}]{}".format(i, item.upper()), end = " ");

[0]Q [5]N [10]I [15]G [20]Z [25]N [30]U [35]V [40]Q [45]C [50]E [55]Q [60]V [65]J [70]O [75]Y [80]H [85]R [90]Z [95]C 

<b>1.4 (3 pts)</b> You have an empty dictionary <i><b>counter</b></i>. Write a for loop that iterates the letters in <b><i>letters</i></b>. For each iteration, check if the current letter is already in <i><b>counter</b></i> as a key. If not, add to <i><b>counter</b></i> the letter as a new key and 1 as its value. If <i><b>counter</b></i> does have the letter as its key, increase the current value for the key by one. 

This way, you will have <i><b>counter</b></i> such that its keys are the unique letters in <b><i>letters</i></b> and its values are the occurrence counts of the keys. <u>For example</u>, the letter c appears three times in <b><i>letters</i></b>, so c is one of the keys in <i><b>counter</b></i> and its value is supposed to be 3. 

In [39]:
# Do not make any change to this cell. Just run this cell.
counter = {}   # alterantively counter = dict()

In [46]:
# Your answer here
for letter in letters:
    if letter in counter:
        counter[letter] +=1;
    else:
        counter[letter] = 1;

In [47]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
counter

{'q': 15,
 'e': 35,
 'f': 15,
 'n': 15,
 'o': 35,
 'g': 15,
 'm': 11,
 'i': 11,
 'r': 15,
 'l': 15,
 'j': 19,
 'z': 23,
 'h': 19,
 'k': 15,
 't': 19,
 'u': 19,
 's': 23,
 'y': 7,
 'v': 11,
 'x': 7,
 'c': 11,
 'd': 11,
 'b': 3,
 'w': 3,
 'a': 3}

### 2. (6 points) Functions

<b>2.1 (2 pts)</b> Write a function <b>get_counter</b> which takes a list of English alphabet strings <b>l</b> as an argument. E.g. <b>letters</b> from Q1 is a list with only English alphabet string elements.   l = ['z', 'c', 'x'] is another example of a list with only English alphabet strings as its elements. 

The output of get_counter must be a dictionary with keys being the unique alphabets in l and the value as the count of that alphabett in the list l. <u>For example</u>, the letter c appears three times in <b><i>letters</i></b>, so c must be one of the keys in the dictionary and its value is supposed to be 3. 

Essentailly we want the answer to Q1.4 written as a function. 

In [48]:
# Your answer here
def get_counter(letters):
    counter = {};
    for letter in letters:
        if letter in counter:
            counter[letter] +=1;
        else:
            counter[letter] = 1;
    return counter;

In [49]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
get_counter(letters)     # Output must be the same as Q1.4

{'q': 4,
 'e': 9,
 'f': 4,
 'n': 4,
 'o': 9,
 'g': 4,
 'm': 3,
 'i': 3,
 'r': 4,
 'l': 4,
 'j': 5,
 'z': 6,
 'h': 5,
 'k': 4,
 't': 5,
 'u': 5,
 's': 6,
 'y': 2,
 'v': 3,
 'x': 2,
 'c': 3,
 'd': 3,
 'b': 1,
 'w': 1,
 'a': 1}

In [50]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
get_counter(['h', 'r', 'r', 's', 'f', 'r', 'a', 'a', 'm', 'a'])     # r must have a count of 3, a must have 3, ...

{'h': 1, 'r': 3, 's': 1, 'f': 1, 'a': 3, 'm': 1}

<b>2.2 (4 pts)</b>  Write a function <b>further_check</b> that takes a list <b>l</b> of numbers (0-100 scale) and a threshold <b>t</b> (0-100 scale) as the arguments. The output must be a list of numbers from <b>l</b> which are less than the threshold <b>t</b>.  

* If there is no number in <b>l</b> less than <b>t</b>, it must return an empty list.  
* If any of the elements in <b>l</b> is neither an integer nor a floating pointer number, it returns the string "Invalid argument!"

Context: The list <b>l</b> consists of performance review scores out of 100. Those who score less than the satisfactory threshold <b>t</b> will be further evaluated. 

In [66]:
# Your answer here
def further_check(l,t):
    th_result = [];
    for item in l:
        if (type(item) not in [int, float]):
                return 'Invalid argument!';
        else: 
            if(item < t):
                th_result.append(item);
    return th_result;
            

In [67]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
further_check([100, 90, 75, 80,64, 55, 48, 37, 30, 0 , 94, 88], 80)     # Expected output: [75, 64, 55, 48, 37, 30, 0]  

[75, 64, 55, 48, 37, 30, 0]

In [68]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
further_check([100, 90, 75, 80,64, 55.7, 48, 37.5, 30, 0.0 , 94, 88], 60)     # Expected output: [55.7, 48, 37.5, 30, 0.0] 

[55.7, 48, 37.5, 30, 0.0]

In [69]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
further_check([75, 80, 64, "90", 75, 80,64, 55, 48, 37], 85)     # Expected output: "Invalid argument!"

'Invalid argument!'

In [70]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
further_check([75, 80, 64, 75, [80] ,64, 55, 48, 37], 85)     # Expected output: "Invalid argument!"

'Invalid argument!'

In [71]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
further_check([90, 75, 80,64, 94, 88], 50)     # Expected output: []

[]

### 3. (11 points) NumPy Application

<b>3.1 (1 pt)</b> Import the NumPy package first. Seed the NumPy random number generator with 2021 and create a 300 x 100 NumPy array <b><i>a</i></b> of <u>random integers</u> between 100 (inclusive) and 1000 (inclusive).

In [90]:
# Your answer here
import numpy as np;
np.random.seed(seed=2021);   
a = np.random.randint(100,1001, (300,100));

In [91]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
a

array([[215, 440, 156, ..., 836, 206, 220],
       [631, 245, 982, ..., 519, 422, 154],
       [367, 462, 533, ..., 940, 984, 900],
       ...,
       [609, 118, 419, ..., 973, 916, 701],
       [906, 537, 145, ..., 616, 681, 863],
       [854, 317, 660, ..., 246, 509, 267]])

<b>3.2 (1 pt)</b> Re-seed the NumPy random number generator with 2021 and create a 100 x 50 NumPy array <b><i>b</i></b> of <u>random numbers</u> that follow a <u>normal distribution</u> with the mean being 0 and the standard deviation being 1.

In [79]:
# Your answer here
np.random.seed(seed=2021);  
b = np.random.normal(0,1, (100,50));

In [80]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
b

array([[ 1.48860905,  0.67601087, -0.41845137, ...,  0.90674805,
        -0.98261724, -0.63316189],
       [ 0.82552024, -1.28449686, -0.34730878, ...,  0.4259372 ,
         0.75663603, -0.99485406],
       [-0.74057432,  0.45823318,  1.2572469 , ...,  1.9178002 ,
         1.02157999, -0.22717161],
       ...,
       [-0.67156736,  1.24476442, -0.4762917 , ...,  0.50723407,
        -0.44109844, -1.26349222],
       [-0.15188585, -1.64899749, -2.75952494, ..., -0.26608747,
         0.69113538, -0.46683453],
       [-1.03039423,  2.19974721, -0.25308104, ...,  1.08242857,
         0.53970457, -0.17037809]])

<b>3.3 (3 pts)</b> Write a function <b><i>sum_product</i></b> that takes two NumPy arrays <b><i>x</i></b> and <b><i>y</i></b> as arguments and returns the <u>sum</u> of the elements in the <u>dot product</u> of <b><i>x</i></b> and <b><i>y</i></b>. If the number of <u>columns</u> of <b><i>x</i></b> does <u>not</u> equal the number of rows of <b><i>y</i></b>, it returns the string "Array shapes not aligned!". 

In [87]:
# Your answer here
def sum_product(x, y):
    xrow, xcolumn = x.shape
    yrow, ycolumn = y.shape
    if(xcolumn != yrow):
        return 'Array shapes not aligned!';
    dot_products = np.dot(x,y);
    return dot_products.sum();
    

In [88]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
p = np.array([[1, 2], [3, 4]])
q = np.array([[6, 5], [4, 3], [2, 1]])

sum_product(p, q)                  # Expected output: 'Array shapes not aligned!'

'Array shapes not aligned!'

In [89]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
p = np.array([[1, 2], [3, 4]])
q = np.array([[4, 3], [2, 1]])

sum_product(p, q)                  # Expected output: 46

46

<b>3.4 (2 pts)</b> Seed the NumPy random number generator with 0. Create a NumPy random array <b> scores </b> of 40 integers between 10 (inclusive) and 25 (inclusive). Conisder these integers as student scores on a test 😉.  
Calculate the <u>min, max, and mean</u> of the <b> scores </b> and <b>print</b> the output as shown below. 

In [111]:
# Your answer here
np.random.seed(seed=0); 
scores = np.random.randint(10,26, 40);

In [112]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
scores

array([22, 25, 15, 10, 13, 21, 13, 17, 19, 13, 15, 12, 14, 17, 16, 18, 18,
       22, 20, 11, 16, 17, 17, 24, 18, 11, 15, 19, 23, 18, 19, 14, 13, 10,
       13, 15, 24, 25, 25, 10])

In [113]:
# Your answer here for printing the score statistics
print("Min: {}".format(scores.min()), end = '\n');
print("Max: {}".format(scores.max()));
print("Mean: {}".format(scores.mean()));

Min: 10
Max: 25
Mean: 16.925


<b>3.5 (1 pt)</b> Use Boolean indexing to access scores greather than or equal to 20 and save it as <b>score20</b>. 

In [115]:
# Your answer here
score20 = scores >= 20;

In [116]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
score20

array([ True,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False, False, False, False,
        True,  True,  True, False])

<b>3.6 (1 pt)</b> It was decided that every student will be awarded an extra credit of 1 pt for the test. Evaluate the updated student scores and save it as <b>newscores</b>. Do not use a for loop. 

In [117]:
# Your answer here
newscores = scores + 1;

In [118]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
newscores

array([23, 26, 16, 11, 14, 22, 14, 18, 20, 14, 16, 13, 15, 18, 17, 19, 19,
       23, 21, 12, 17, 18, 18, 25, 19, 12, 16, 20, 24, 19, 20, 15, 14, 11,
       14, 16, 25, 26, 26, 11])

<b>3.7 (2 pts)</b> We have been told that <b>probability</b> of getting heads (or tails) on a fair coin toss is 0.5. We would like to verify this claim uisng our Python skills. We will simulate a large number (n = 100000) of coin tosses in Python and count how many time we got the heads. 

We simluate a coin toss by randomly picking an integer from array [0, 1] and if it's 1, we count it as a heads. 

<b>Complete</b> the code given below to evaluate the <b>probability</b> of heads. 

In [132]:
# complete and run this code to get the answer

np.random.seed(seed=0)
n = 100000    # number of coin tosses
count = 0    # to keep count of # of heads

for i in range(n):        # running the for loop n times
    # write down code to randomly chose an integer from an array [0,1]  and save it as toss
    toss = np.random.randint(0,2,1);
    # write down an if condition for checking if toss is 1 
    if(toss == 1):
        # write down code to update count by 1 if toss is 1
        count +=1;
        
Probability = count/n   # probability of heads 
Probability             # expect it to be close to 0.5

0.50063

### 4. (1 pt) Which topic(s) have you found most interesting in the course so far and why? If you are new to programming, describe your programming experience so far. 

Your Answer: I really like list slicing. I am a java developer but to make simple list boolean indexing, addition of list... , i need to write minimum of 2 lines code to do same in Java. Also numpy libraries are very interesting. 

<b>4.1 Survey</b> How long did it take you to complete the exam?

In [ ]:
Time =   1.5   # enter in hours   
Time

## * Make sure to Restart & Run All to create a clean version of this notebook!