# Data Programming in Python | BAIS:6040
# Homework 3. User-Defined Functions, Exceptions, and Numpy

10 questions, 6 points in total

## Instructions

- Fill in the Python statements needed to complete all the questions below. 
- Program everything inside this notebook. 
- Use only one cell per question. 
- Each code cell must be run with no errors.
- Do not contain any unnecessary code in your answer. (Only the final outcome will be regarded as your answer.)
- If the question requests that you store information in a certain variable, use the specific variables name (case sensitive).
- All problems must be solved in a programmable way.
- When you are done, make sure to save your notebook and then click Restart & Run All before subimission to create a clean version.

## Questions

1\. (0.6 pts) Write a function `get_stats` that takes a list `l` of integers as an argument and returns a tuple of the min, max, and sum of only the positive numbers in `l` for each. You may need a temporary list like `l_tmp` to store only the positive numbers in `l`. Use a for loop to fill in `l_tmp`.

Note: Do not use the <b>print</b> function in this question. The function returns a tuple, not prints it. 

In [1]:
# Your answer here
def get_stats(l):
    l_tmp = [];
    for item in l:
        if(item > 0):
            l_tmp.append(item);
            
    l_tmp.sort(); 
    t = tuple([l_tmp[0], l_tmp[-1], sum(l_tmp)]);
    return t;
            

In [2]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
get_stats([1, 3, 2])            # Output: (1, 3, 6)

(1, 3, 6)

In [3]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
get_stats([-1, 1, 0, 3, 2])     # Output: (1, 3, 6)

(1, 3, 6)

2\. (0.6 pts) Write a function `get_stats2` that works the same as `get_stats` above, but, additionally, it returns the  '*Invalid value!*' string when it finds any non-integer in `l`. Use a for loop to check if each item in `l` is an integer.

Note: Do not use the <b>print</b> function in this question. The function returns either a tuple or a string, not prints it. 

In [4]:
# Your answer here
def get_stats2(l):
    l_tmp = [];
    for item in l:
        if(type(item) == int):
            if(item > 0):
                l_tmp.append(item);
        else:
            return 'Invalid value!';
            
    l_tmp.sort(); 
    t = tuple([l_tmp[0], l_tmp[-1], sum(l_tmp)]);
    return t;

In [5]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
get_stats2([-1, 1, 0, 3, 2])     # Output: (1, 3, 6)

(1, 3, 6)

In [6]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
get_stats2([-1, 1, 0.0, 3, 2])   # Output: 'Invalid value!'.

'Invalid value!'

In [7]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
get_stats2([-1, 1, "0", 3, 2])   # Output: 'Invalid value!'.

'Invalid value!'

3\. (0.6 pts) Write a function `truncate` that takes a string `s` and an integer `limit` as arguments and returns the string as it is if the length of the string is equal to or less than `limit`. If the length is greater than `limit`, it only takes the `limit`-length leading substring of `s` (i.e., from the index position 0 to `limit` -1) replacing the rest of `s` with '...' and returns that truncated string. Set the default value for `limit` to 50.

Note: Do not use the <b>print</b> function in this question. The function returns a string, not prints anything. 

In [8]:
# Your answer here
def truncate(s, limit = 50):
    if(len(s) <= limit):
        return s;
    else:
        return s[:limit-len(s)]+'...';

In [9]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
truncate("I'm learning Python data analytics.", 100)

# Output: "I'm learning Python data analytics."

"I'm learning Python data analytics."

In [10]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
truncate("I'm learning Python data analytics.", 10)

# Output: "I'm learni..."

"I'm learni..."

In [11]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
truncate("I'm learning Python data analytics. Python is a general purpose programming language.")

# Output: "I'm learning Python data analytics. Python is a ge..."

"I'm learning Python data analytics. Python is a ge..."

4\. (0.6 pts) Create a dictionary `kwargs` that sets the argument values of `s` to any string longer than 30 characters and `limit` to 30 and then call the `truncate` function by passing `kwargs`.

In [12]:
# Your answer here
s = "I'am student of IOWA university and learning Python as a part of my dueal masters MSBA"
kwargs = {"s":s}
truncate(kwargs["s"], 30)

"I'am student of IOWA universit..."

5\. (0.6 pts) To use NumPy, import the NumPy package as np.

In [13]:
# Your answer here
import numpy as np

6\. (0.6 pts) Set the random seed to 0 and then create a 10 x 10 array `x` of random integers between 1 (inclusive) and 100 (inclusive).

In [14]:
# Your answer here
np.random.seed(seed = 0)
x = np.random.randint(1, 101, (10, 10))

In [15]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
x

array([[ 45,  48,  65,  68,  68,  10,  84,  22,  37,  88],
       [ 71,  89,  89,  13,  59,  66,  40,  88,  47,  89],
       [ 82,  38,  26,  78,  73,  10,  21,  81,  70,  80],
       [ 48,  65,  83, 100,  89,  50,  30,  20,  20,  15],
       [ 40,  33,  66,  10,  58,  33,  32,  75,  24,  36],
       [ 76,  56,  29,  35,   1,   1,  37,  54,   6,  39],
       [ 18,  80,   5,  43,  59,  32,   2,  66,  42,  58],
       [ 36,  12,  47,  83,  92,   1,  15, 100,  54,  13],
       [ 43,  85,  76,  69,   7,  69,  48,   4,  77,  53],
       [ 79,  16,  21, 100,  59,  24,  80,  14,  86,  49]])

7\. (0.6 pts) Create a 10 x 10 array `y` of integers from 100 (inclusive) to 1 (inclusive), such that the first row has integers from 100 to 91, the second row from 90 to 81, and so on and so forth. Note that order of values matters. 

In [16]:
# Your answer here
y = np.arange(100,0,-1).reshape(10,10)

In [17]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
y

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

8\. (0.6 pts) Select all the values that are in the first 3 rows and the last 7 columns of `x` and save the resulting array in `x_top_right`. Select all the values that are in the last 7 rows and the first 3 columns of `y` and save the resulting array in `y_bottom_left`.

In [18]:
# Your answer here
x_top_right = y[:3, 7:]
y_bottom_left = y[7:, :3]

In [19]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
x_top_right

array([[93, 92, 91],
       [83, 82, 81],
       [73, 72, 71]])

In [20]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
y_bottom_left

array([[30, 29, 28],
       [20, 19, 18],
       [10,  9,  8]])

9\. (0.6 pts) Before we calculate the dot product of `x_top_right` and `y_bottom_left`, we want to confirm that the number of columns of `x_top_right` equals the number of rows of `y_bottom_left`. Compare the two values using the equality operator (==) and save the resulting True value in `ans9`. Do not directly put their values (i.e., 7) in the comparison.

In [21]:
# Your answer here
xrow, xcolumn = x_top_right.shape
yrow, ycolumn = y_bottom_left.shape
ans9 = (xcolumn == yrow)

In [22]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans9

True

10\. (0.6 pts) Calculate the dot product of `x_top_right` and `y_bottom_left` and then save the resulting array in the variable `dot_prod`. 

In [23]:
# Your answer here
dot_prod = np.dot(x_top_right, y_bottom_left)

In [24]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
dot_prod

array([[5540, 5264, 4988],
       [4940, 4694, 4448],
       [4340, 4124, 3908]])

### Now that you have completed all the questions, click Kernel > Restart & Run All to creat a clean version of this notebook and check if all cells have run as expected. 